version: "3.9"

services:
  ozon_fbo_advisor:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ozon_fbo_advisor
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
      - ./src:/app/src
    restart: always
    healthcheck:
      test: ["CMD", "python", "-c", "print('healthy')"]
      interval: 60s
      timeout: 10s
      retries: 3
    environment:
      - TZ=${TZ}
    command: ["python", "main.py"]

volumes:
  logs:
